categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
exclude-labels:
  - "skip-changelog"
template: |
  ## Changes

  $CHANGES
