name: Deploy Site

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@2.0.0
    - name: Install Dependencies
      run: npm i
    - name: Deploy site
      run: npm run site:deploy
