name: CI

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: mig4/setup-bats@v1.0.1
    - name: Setup BATS testing framework
      run: $PWD && bats ./tests/index.bats
