name: CI

on: [pull_request]

jobs:
  test:

    runs-on: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Bats
      run: ./scripts/install_bats.sh
    - name: Run tests
      run: bats ./tests/index.bats
