name: CI

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Know my location
      run: $PWD
    - name: Install Bats
      run: ./scripts/install_bats.sh
    - name: Run tests
      run: bats ./tests/index.sh
